name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          architecture: 'x64'

      - name: Build with Maven
        run: mvn -B package --file IzvorniKod/backend/prijava/pom.xml

      - name: Run tests
        run: mvn verify --file IzvorniKod/backend/prijava/pom.xml
